import assert from "node:assert/strict";
import { analyze, consensus, type Vote } from "../lib/polis-math.ts";
assert.equal(analyze([],[]).status,"collecting");
assert.equal(consensus([{agree:3,seen:4},{agree:4,seen:4}]),4/6*5/6);
const ids=Array.from({length:12},(_,i)=>"p"+i);
const votes:Vote[]=[];
for(let s=0;s<12;s++)for(let p=0;p<12;p++)votes.push({session_id:"s"+s.toString().padStart(2,"0"),opinion_id:"p"+p,value:p===0?-1:(s<6?(p%2?-1:1):(p%2?1:-1))});
let a=analyze(votes,ids,"s00");
assert.equal(a.status,"ready");assert.equal(a.points.length,12);assert.equal(a.points.filter(p=>p.mine).length,1);assert.equal(a.groups.length,2);assert.equal(a.bridges[0].id,"p0");assert.ok(a.points.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));
assert.equal(analyze(votes.map(v=>({...v,value:-1})),ids).status,"uniform");
assert.equal(analyze(votes.map(v=>({...v,value:0})),ids).status,"collecting");
assert.equal(analyze(votes.filter(v=>v.session_id<"s07"),ids).status,"collecting");
const sparse=votes.filter(v=>v.opinion_id==="p0"||Number(v.opinion_id.slice(1))%5!==Number(v.session_id.slice(1))%5);
assert.equal(analyze(sparse,ids).status,"ready");
const missingConsensus=votes.filter(v=>!(v.opinion_id==="p0"&&v.session_id>="s06"));
assert.ok(!analyze(missingConsensus,ids).bridges.some(b=>b.id==="p0"));
const disconnected=votes.map(v=>({...v,opinion_id:Number(v.session_id.slice(1))<6?v.opinion_id:"q"+v.opinion_id}));
assert.equal(analyze(disconnected,[...ids,...ids.map(i=>"q"+i)]).status,"collecting");
assert.deepEqual(analyze([...votes,...votes.map(v=>({...v,opinion_id:'unrelated',value:2}))],[...ids,'unrelated'],'s00'),a);
assert.equal(analyze(votes.map(v=>({...v,value:2})),ids).eligible,0);
const flagConsensus=votes.map(v=>v.opinion_id==='p0'&&v.session_id>='s06'?{...v,value:2}:v);
assert.deepEqual(analyze(flagConsensus,ids),analyze(missingConsensus,ids));
console.log("PASS: PCA, separated clusters, consensus, sparse/missing votes, insufficient data, uniform/pass-only responses, disconnected overlap.");
