import { sqliteTable, text, integer, real, primaryKey, index, uniqueIndex, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
export const sessions=sqliteTable("sessions",{id:text("id").primaryKey(),tokenHash:text("token_hash").notNull().unique(),phase:text("phase").notNull().default("active"),createdAt:integer("created_at").notNull(),endedAt:integer("ended_at"),noticeVersion:text("notice_version"),lastSeenAt:integer("last_seen_at"),approvedVoteCount:integer("approved_vote_count").notNull().default(0)});
export const opinions=sqliteTable("opinions",{id:text("id").primaryKey(),tagId:text("tag_id").notNull(),text:text("text").notNull(),kind:text("kind").notNull(),authorSession:text("author_session").references(()=>sessions.id),sourceIds:text("source_ids").notNull().default("[]"),createdAt:integer("created_at").notNull(),status:text("status").notNull().default("approved"),revision:integer("revision").notNull().default(0),reviewedUnrelated:integer("reviewed_unrelated").notNull().default(0),reviewedReports:integer("reviewed_reports").notNull().default(0),agreeCount:integer("agree_count").notNull().default(0),disagreeCount:integer("disagree_count").notNull().default(0),passCount:integer("pass_count").notNull().default(0),unrelatedCount:integer("unrelated_count").notNull().default(0)},t=>[index("idx_opinions_author").on(t.authorSession),index("idx_opinions_status").on(t.status),index("idx_opinions_kind").on(t.kind)]);
export const votes=sqliteTable("votes",{sessionId:text("session_id").notNull().references(()=>sessions.id),opinionId:text("opinion_id").notNull().references(()=>opinions.id),value:integer("value").notNull(),unrelated:integer("unrelated",{mode:"boolean"}).notNull().default(false),createdAt:integer("created_at").notNull(),impressionId:text("impression_id")},t=>[primaryKey({columns:[t.sessionId,t.opinionId]}),index("idx_votes_opinion").on(t.opinionId),index("idx_votes_impression").on(t.impressionId),index("idx_votes_opinion_session").on(t.opinionId,t.sessionId),check("vote_value",sql`${t.value} IN (-1,0,1)`)]);
export const impressions=sqliteTable("impressions",{id:text("id").primaryKey(),sessionId:text("session_id").notNull().references(()=>sessions.id),opinionId:text("opinion_id").notNull().references(()=>opinions.id),sequence:integer("sequence").notNull(),textSnapshot:text("text_snapshot").notNull(),tagSnapshot:text("tag_snapshot").notNull(),sourceSnapshot:text("source_snapshot").notNull(),kindSnapshot:text("kind_snapshot").notNull(),routingVersion:text("routing_version").notNull(),probability:real("probability").notNull(),candidates:text("candidates").notNull(),issuedAt:integer("issued_at").notNull(),displayedAt:integer("displayed_at"),answeredAt:integer("answered_at"),retiredAt:integer("retired_at")},t=>[uniqueIndex("idx_impressions_sequence").on(t.sessionId,t.sequence),index("idx_impressions_open").on(t.sessionId,t.answeredAt,t.retiredAt),index("idx_impressions_opinion_open").on(t.opinionId,t.answeredAt,t.retiredAt)]);
export const events=sqliteTable("events",{id:text("id").primaryKey(),sessionId:text("session_id").notNull().references(()=>sessions.id),type:text("type").notNull(),impressionId:text("impression_id"),snapshotId:text("snapshot_id"),clientAt:integer("client_at"),clientSequence:integer("client_sequence"),createdAt:integer("created_at").notNull()},t=>[index("idx_events_session_time").on(t.sessionId,t.createdAt),index("idx_events_impression_type").on(t.impressionId,t.type)]);
export const resultSnapshots=sqliteTable("result_snapshots",{id:text("id").primaryKey(),payload:text("payload").notNull(),createdAt:integer("created_at").notNull()});
export const reports=sqliteTable("reports",{id:text("id").primaryKey(),sessionId:text("session_id").notNull().references(()=>sessions.id),opinionId:text("opinion_id").notNull().references(()=>opinions.id),category:text("category").notNull(),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("idx_reports_dedup").on(t.sessionId,t.opinionId),index("idx_reports_opinion").on(t.opinionId)]);
export const moderationActions=sqliteTable("moderation_actions",{id:text("id").primaryKey(),opinionId:text("opinion_id").notNull(),action:text("action").notNull(),reason:text("reason").notNull(),actor:text("actor").notNull(),runUrl:text("run_url").notNull(),previousStatus:text("previous_status").notNull(),nextStatus:text("next_status").notNull(),revision:integer("revision").notNull(),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("idx_moderation_revision").on(t.opinionId,t.revision)]);
export const releases=sqliteTable("releases",{id:text("id").primaryKey(),sha256:text("sha256").notNull(),objectKey:text("object_key").notNull(),status:text("status").notNull().default("draft"),createdAt:integer("created_at").notNull(),publishedAt:integer("published_at"),summary:text("summary").notNull(),opinionRevisions:text("opinion_revisions").notNull(),prepareRunUrl:text("prepare_run_url"),publishRunUrl:text("publish_run_url"),publicationReason:text("publication_reason"),schemaVersion:integer("schema_version").notNull().default(2),phase:text("phase").notNull().default("done"),cursor:integer("cursor").notNull().default(0),buildRevision:integer("build_revision").notNull().default(0),watermarks:text("watermarks").notNull().default("{}"),counts:text("counts").notNull().default("{}"),moderationRevision:integer("moderation_revision").notNull().default(0),actor:text("actor").notNull(),reason:text("reason").notNull()});

export const communityState=sqliteTable("community_state",{id:integer("id").primaryKey(),votes:integer("votes").notNull().default(0),sessions:integer("sessions").notNull().default(0),revision:integer("revision").notNull().default(0),moderationRevision:integer("moderation_revision").notNull().default(0),ready:integer("ready").notNull().default(0),backfillPhase:text("backfill_phase").notNull().default("opinions"),backfillCursor:integer("backfill_cursor").notNull().default(0)});
export const analysisCache=sqliteTable("analysis_cache",{id:integer("id").primaryKey(),snapshotId:text("snapshot_id"),revision:integer("revision").notNull().default(-1),moderationRevision:integer("moderation_revision").notNull().default(-1),computedAt:integer("computed_at").notNull().default(0),completedDay:text("completed_day"),leaseToken:text("lease_token"),leaseUntil:integer("lease_until").notNull().default(0)});
export const releaseOpinions=sqliteTable("release_opinions",{releaseId:text("release_id").notNull(),opinionId:text("opinion_id").notNull(),revision:integer("revision").notNull(),payload:text("payload").notNull()},t=>[primaryKey({columns:[t.releaseId,t.opinionId]})]);
export const releaseParts=sqliteTable("release_parts",{releaseId:text("release_id").notNull(),partId:text("part_id").notNull(),kind:text("kind").notNull(),objectKey:text("object_key").notNull(),sha256:text("sha256").notNull(),rowCount:integer("row_count").notNull(),byteLength:integer("byte_length").notNull()},t=>[primaryKey({columns:[t.releaseId,t.partId]})]);
